changelog:
  exclude:
    authors:
      - github-actions
  categories:
    - title: New Features 🎉
      labels:
        - "enhancement"
    - title: Bug Fix 💊
      labels:
        - "bug"
    - title: Refactoring ♻️
      labels:
        - "refactoring"
    - title: Other Changes 🛠
      labels:
        - "*"
