version: "3.0"

services:
  api:
    build:
      context: ./docker/api
      dockerfile: Dockerfile
    volumes:
      - ./api:/works/app:cached
      - ./scripts:/works/scripts:cached
    working_dir: /works/app
    command: bash -c "../scripts/run.sh"
    ports:
      - 8080:8080
