name: Build & Deploy Eatit Monitoring

on:
  push:
    branches:
      - prod
    paths:
      - monitoring/**
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-22.04
    timeout-minutes: 15
    defaults:
      run:
        working-directory: monitoring
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js 20.11.1
        uses: actions/setup-node@v4
        with:
          node-version: '20.11.1'

      - name: Monorepo install
        uses: ./.github/actions/yarn-nm-install
        with:
          cwd: 'frontend'
          enable-corepack: true
          cache-node-modules: false
          cache-install-state: false

      - name: Create .clasprc.json
        run: |
          echo "${{ secrets.GO3KE_BASE64 }}" | base64 --decode > ~/.clasprc.json

      - name: Create .clasp.json
        run: |
          cat > .clasp.json <<EOF
          {
            "scriptId": "${{ secrets.EATIT_MONITORING_SCRIPT_ID }}",
            "rootDir": "./dist"
          }
          EOF

      - name: Build & Deploy
        run: |
          yarn push
