name: Deploy to Chrome web store

on:
  push:
    branches:
      - prod
    paths:
      - frontend/**
  workflow_dispatch:

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: frontend
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js 20.11.1
        uses: actions/setup-node@v4
        with:
          node-version: '20.11.1'

      - name: Create dot env file
        run: |
          touch .env.production
          echo "PLASMO_PUBLIC_API_BASE_URL=${{ secrets.PLASMO_PUBLIC_API_BASE_URL }}" >> .env.production

      - name: Monorepo install
        uses: ./.github/actions/yarn-nm-install
        with:
          cwd: './frontend'
          enable-corepack: true
          cache-node-modules: false
          cache-install-state: false

      - name: Build
        run: yarn build

      - name: Install zip
        uses: montudor/action-zip@v0.1.1

      - name: Zip output
        run: zip -qq -r release.zip *
        working-directory: frontend/build/chrome-mv3-prod

      - name: Upload to Chrome Web Store
        uses: mobilefirstllc/cws-publish@latest
        with:
          action: publish
          client_id: ${{ secrets.CLIENT_ID }}
          client_secret: ${{ secrets.CLIENT_SECRET }}
          refresh_token: ${{ secrets.REFRESH_TOKEN }}
          extension_id: ${{ secrets.EXTENSION_ID }}
          zip_file: './frontend/build/chrome-mv3-prod/release.zip'
